name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '5.0.x'
    
    - name: Build and Test
      run: |
        dotnet restore
        dotnet build
        dotnet test
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '5.0.x'
    
    - name: Publish Application
      run: dotnet publish -c Release -o publish/
    
    - name: Deploy to Test Environment
      run: ./deploy-script.sh
